### ISSUE TITLE
Accès aux couches OSM impossible

### ISSUE THREAD

**Issue by jbdesbas** [geo2france/geo2france-qgis3-plugin#4]
Bonjour,

En version 0.9.1 avec QGIS 3.16.2 : il est impossible de charger les couches OSM

>  CRITICAL    Couche non valide : WMS provider Impossible de calculer l'emprise
>              Raster layer Le fournisseur de données n'est pas valide (prestataire : wms, URI : crs=epsg:2154&featureCount=10&format=image/jpeg&layers=bright&maxHeight=256&maxWidth=256&styles=&url=https://osm.geo2france.fr/mapproxy/service

Bonne journée !

**Comment by vfabry** [comment]
Bonjour,
Le problème a été corrigé : est-ce que vous pouvez recharger le plugin ?

**Comment by jbdesbas** [comment]
Parfait ça fonctionne, merci ! (en rechargeant le fichier de configuration dans les paramètres du plugin)

**Comment by bchartier** [comment]
Je profite de ce ticket pour expliquer le pourquoi du comment... (cela pourra être utile pour plus tard).
Les modifications opérées sont visibles dans ce commit : 26a1b75
2 choses donc :
* le service qui produit le fond cartographique d'OSM a changé (pas le même moteur ni le même point d'accès)
* pour certains couches le code EPSG doit être écrit obligatoirement en majuscules `EPSG:2154` au lieu de `epsg:2154`.

**Comment by jbdesbas** [comment]
Merci pour ces explications
Ce qui est curieux c'est que ce problème a eu lieu sur deux installations "fraîches" ce jour, alors que le commit date de 4 jours. La version sur le dépôt n'est pas la plus récente ?
